#!/bin/bash

JAR=bin/asgard-standalone.jar

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

if [ -z "$ZK_CONN_STRING" ]
then
    echo "Using local ZK => localhost:2181"
    export ZK_CONN_STRING="localhost:2181"
fi

if [ -z "$ZK_AES_KEY" ]
then
    echo "Nope. ZK_AES_KEY not set."
    exit
fi

# Download the jar if needed
if [ ! -f "$JAR" ]
then
    echo "Downloading Asgard, this will take a while..."
    wget https://github.com/Netflix/asgard/releases/download/1.5.1/asgard-standalone.jar -O "$JAR"
fi

echo "Checking the config here and there"

# ~/.asgard
ln -sfh $DIR/asgard-home $HOME/.asgard

echo "Running Asgard..."

# Run, Forest, Run!
java -Xmx1024M -XX:MaxPermSize=256m -Djava.endorsed.dirs=$DIR/dependencies -jar $JAR
