#!/bin/bash

JAR=bin/asgard-standalone.jar

if [[ "$(uname)" == "Darwin" ]]
then
    JAVA_HOME=/Library/Java/Home
else
    echo "You may wanna export your JAVA_HOME so we know where to link our dependencies."
    exit
fi

if [ -z "$ZK_CONN_STRING" ]
then
    echo "Using local ZK => localhost:2181"
    export ZK_CONN_STRING="localhost:2181"
fi

# Download the jar if needed
if [ ! -f "$JAR" ]
then
    echo "Downloading Asgard, this will take a while..."
    wget https://github.com/Netflix/asgard/releases/download/1.5.1/asgard-standalone.jar -O "$JAR"
fi

echo "Checking the config here and there"

# ~/.asgard
ln -sfh $(pwd)/asgard-home $HOME/.asgard

# Add plugins's depedencies jars
for file in dependencies/*
do
    sudo ln -sf $(pwd)/$file $JAVA_HOME/lib/endorsed
done

echo "Running Asgard..."

# Run, Forest, Run!
java -Xmx1024M -XX:MaxPermSize=256m -jar $JAR
